package checksetter

import (
	"fmt"
	"go/ast"

	"github.com/nickwells/check.mod/v2/check"
)

const (
	int64CFName = "check.Int64"
	int64CFDesc = "int check func"
)

type int64CFMaker func(*ast.CallExpr, string) (check.Int64, error)

var int64CFArgsToFunc map[string]int64CFMaker

func init() {
	int64CFArgsToFunc = map[string]int64CFMaker{
		"":                       makeInt64CF,
		"int":                    makeInt64CFInt64,
		"int, int":               makeInt64CFInt64Int64,
		int64CFName + ", string": makeInt64CFInt64CFStr,
		int64CFName + " ...":     makeInt64CFInt64CFList,
	}
}

var int64CFNoParam = map[string]check.Int64{
	"OK": check.ValOK[int64],
}

var int64CFInt64 = map[string]func(int64) check.Int64{
	"EQ":          check.ValEQ[int64],
	"GT":          check.ValGT[int64],
	"GE":          check.ValGE[int64],
	"LT":          check.ValLT[int64],
	"LE":          check.ValLE[int64],
	"Divides":     check.ValDivides[int64],
	"IsAMultiple": check.ValIsAMultiple[int64],
}

var int64CFInt64Int64 = map[string]func(int64, int64) check.Int64{
	"Between": check.ValBetween[int64],
}

var int64CFInt64CFStr = map[string]func(check.Int64, string) check.Int64{
	"Not": check.Not[int64],
}

var int64CFInt64CFList = map[string]func(...check.Int64) check.Int64{
	"And": check.And[int64],
	"Or":  check.Or[int64],
}

// makeInt64CF returns an Int64 checker corresponding to the given name - this
// is for checkers that are named directly and are not generated by calling a
// function
func makeInt64CF(_ *ast.CallExpr, fName string) (cf check.Int64, err error) {
	errIntro := fmt.Sprintf("can't make the %s func: %s():",
		int64CFName, fName)

	if f, ok := int64CFNoParam[fName]; ok {
		return f, nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro)
}

// makeInt64CFInt64 returns an Int64 checker corresponding to the given name -
// this is for checkers that take a single integer parameter
func makeInt64CFInt64(e *ast.CallExpr, fName string) (cf check.Int64, err error) {
	var i int64
	errIntro := func() string {
		return fmt.Sprintf("can't make the %s func: %s(%d):",
			int64CFName, fName, i)
	}
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v", errIntro(), r)
		}
	}()

	if err = checkArgCount(e, 1); err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	i, err = getArgAsInt64(e, 0)
	if err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	if f, ok := int64CFInt64[fName]; ok {
		return f(i), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro())
}

// makeInt64CFInt64Int64 returns an Int64 checker corresponding to the given name
// - this is for checkers that take two integer parameters
func makeInt64CFInt64Int64(e *ast.CallExpr, fName string) (cf check.Int64, err error) {
	var i, j int64
	errIntro := func() string {
		return fmt.Sprintf("can't make the %s func: %s(%d, %d):",
			int64CFName, fName, i, j)
	}
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v",
				errIntro(), r)
		}
	}()

	if err = checkArgCount(e, 2); err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	i, err = getArgAsInt64(e, 0)
	if err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}
	j, err = getArgAsInt64(e, 1)
	if err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	if f, ok := int64CFInt64Int64[fName]; ok {
		return f(i, j), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro())
}

// makeInt64CFInt64CFStr returns an Int64 checker corresponding to the given
// name - this is for checkers that take an Int64 check func and a string
// parameter
func makeInt64CFInt64CFStr(e *ast.CallExpr, fName string) (cf check.Int64, err error) {
	var s string
	errIntro := func() string {
		return fmt.Sprintf("can't make the %s func: %s(%s, %s):",
			int64CFName, fName, int64CFName, s)
	}
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v", errIntro(), r)
		}
	}()

	if err = checkArgCount(e, 2); err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	icf, err := getFuncInt64CF(e.Args[0])
	if err != nil {
		return nil, fmt.Errorf("%s can't convert argument %d to %s: %s",
			errIntro(), 0, int64CFName, err)
	}
	s, err = getString(e.Args[1])
	if err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	if f, ok := int64CFInt64CFStr[fName]; ok {
		return f(icf, s), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro())
}

// makeInt64CFInt64CFList returns an Int64 checker corresponding to the given
// name - this is for checkers that take a list of int64 check funcs
func makeInt64CFInt64CFList(e *ast.CallExpr, fName string) (cf check.Int64, err error) {
	errIntro := "can't make the " + int64CFName +
		" func: " + fName + "(" + int64CFName + " ...):"
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v", errIntro, r)
		}
	}()

	fArgs := make([]check.Int64, 0, len(e.Args))
	for i, argExpr := range e.Args {
		scf, err := getFuncInt64CF(argExpr)
		if err != nil {
			return nil, fmt.Errorf("%s can't convert argument %d to %s: %s",
				errIntro, i, int64CFName, err)
		}
		fArgs = append(fArgs, scf)
	}

	if f, ok := int64CFInt64CFList[fName]; ok {
		return f(fArgs...), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro)
}

// int64CFParse returns a slice of int64 check functions and a nil error if
// the string is successfully parsed or nil and an error if the string
// couldn't be converted to a slice of check functions.
func int64CFParse(s string) ([]check.Int64, error) {
	elts, err := getElts(s, int64CFDesc)

	if err != nil {
		return nil, err
	}

	rval := make([]check.Int64, 0, len(elts))

	for _, elt := range elts {
		f, err := getFuncInt64CF(elt)
		if err != nil {
			return nil, fmt.Errorf("bad function: %s", err)
		}
		rval = append(rval, f)
	}

	return rval, nil
}

// getFuncInt64CF will process the expression and return an Int64 checker or
// nil
func getFuncInt64CF(elt ast.Expr) (cf check.Int64, err error) {
	e, ok := elt.(*ast.CallExpr)
	if !ok {
		return nil, fmt.Errorf("unexpected type: %T", elt)
	}

	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("Cannot create the %s func: %v", int64CFName, r)
		}
	}()

	fd, err := getFuncDetails(e, int64CFName)
	if err != nil {
		return nil, err
	}

	maker, ok := int64CFArgsToFunc[fd.expectedArgs]
	if !ok {
		return nil, fmt.Errorf("%s has an unrecognised argument list: %s",
			fd.name, fd.expectedArgs)
	}

	return maker(e, fd.name)
}
