package checksetter

import (
	"fmt"
	"go/ast"
	"regexp"

	"github.com/nickwells/check.mod/v2/check"
)

const (
	strCFName = "check.String"
	strCFDesc = "string-checking functions"
)

type strCFMaker func(*ast.CallExpr, string) (check.String, error)

var strCFArgsToFunc map[string]strCFMaker

func init() {
	strCFArgsToFunc = map[string]strCFMaker{
		"":                     makeStrCF,
		intCFName:              makeStrCFIntCF,
		"regexp, string":       makeStrCFREStr,
		"string":               makeStrCFStr,
		strCFName + ", string": makeStrCFStrCFStr,
		strCFName + " ...":     makeStrCFStrCFList,
	}
}

var strCFNoParam = map[string]check.String{
	"OK": check.ValOK[string],
}

var strCFIntCF = map[string]func(check.ValCk[int]) check.String{
	"Length": check.StringLength[string],
}

var strCFStr = map[string]func(string) check.String{
	"HasPrefix": check.StringHasPrefix[string],
	"HasSuffix": check.StringHasSuffix[string],
	"EQ":        check.ValEQ[string],
}

var strCFREStr = map[string]func(*regexp.Regexp, string) check.String{
	"MatchesPattern": check.StringMatchesPattern[string],
}

var strCFStrCFStr = map[string]func(check.String, string) check.String{
	"Not": check.Not[string],
}

var strCFStrCFList = map[string]func(...check.String) check.String{
	"And": check.And[string],
	"Or":  check.Or[string],
}

// makeStrCF returns a String checker corresponding to the given name - this
// is for checkers that are named directly and are not generated by calling a
// function
func makeStrCF(e *ast.CallExpr, fName string) (cf check.String, err error) {
	errIntro := fmt.Sprintf("can't make the %s func: %s():", strCFName, fName)

	if e != nil {
		if err = checkArgCount(e, 0); err != nil {
			return nil, fmt.Errorf("%s %s", errIntro, err)
		}
	}

	if f, ok := strCFNoParam[fName]; ok {
		return f, nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro)
}

// makeStrCFIntCF returns a String checker corresponding to the given name -
// this is for checkers that take a single Int checker parameter
func makeStrCFIntCF(e *ast.CallExpr, fName string) (cf check.String, err error) {
	errIntro := func() string {
		return fmt.Sprintf("can't make the %s func: %s(...):",
			strCFName, fName)
	}
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v", errIntro(), r)
		}
	}()

	if err = checkArgCount(e, 1); err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	var icf check.ValCk[int]
	icf, err = getFuncIntCF(e.Args[0])
	if err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	if f, ok := strCFIntCF[fName]; ok {
		return f(icf), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro())
}

// makeStrCFStr returns a String checker corresponding to the
// given name - this is for checkers that take a single string parameter
func makeStrCFStr(e *ast.CallExpr, fName string) (cf check.String, err error) {
	var s string
	errIntro := func() string {
		return fmt.Sprintf("can't make the %s func: %s(%s):",
			strCFName, fName, s)
	}
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v", errIntro(), r)
		}
	}()

	if err = checkArgCount(e, 1); err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	s, err = getString(e.Args[0])
	if err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	if f, ok := strCFStr[fName]; ok {
		return f(s), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro())
}

// makeStrCFREStr returns a String checker corresponding to the given name -
// this is for checkers that take a regular expression and a single string
// parameter
func makeStrCFREStr(e *ast.CallExpr, fName string) (cf check.String, err error) {
	var reStr, reDesc string
	errIntro := func() string {
		return fmt.Sprintf("can't make the %s func: %s(%s, %s):",
			strCFName, fName, reStr, reDesc)
	}
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v", errIntro(), r)
		}
	}()

	if err = checkArgCount(e, 2); err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	reStr, err = getString(e.Args[0])
	if err != nil {
		return nil, fmt.Errorf("%s can't get the regexp: %s", errIntro(), err)
	}

	re, err := regexp.Compile(reStr)
	if err != nil {
		return nil, fmt.Errorf("%s the regexp doesn't compile: %s",
			errIntro(), err)
	}

	reDesc, err = getString(e.Args[1])
	if err != nil {
		return nil, fmt.Errorf("%s can't get the regexp description: %s",
			errIntro(), err)
	}

	if f, ok := strCFREStr[fName]; ok {
		return f(re, reDesc), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro())
}

// makeStrCFStrCFStr returns a String checker corresponding to the given name
// - this is for checkers that take a string check func and a string
// parameter
func makeStrCFStrCFStr(e *ast.CallExpr, fName string) (cf check.String, err error) {
	var s string
	errIntro := func() string {
		return fmt.Sprintf("can't make the %s func: %s(%s, %s):",
			strCFName, fName, strCFName, s)
	}
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v", errIntro(), r)
		}
	}()

	if err = checkArgCount(e, 2); err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	scf, err := getFuncStrCF(e.Args[0])
	if err != nil {
		return nil, fmt.Errorf("%s can't convert argument %d to %s: %s",
			errIntro(), 0, strCFName, err)
	}
	s, err = getString(e.Args[1])
	if err != nil {
		return nil, fmt.Errorf("%s %s", errIntro(), err)
	}

	if f, ok := strCFStrCFStr[fName]; ok {
		return f(scf, s), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro())
}

// makeStrCFStrCFList returns a String checker corresponding to the given
// name - this is for checkers that take a list of string check funcs
func makeStrCFStrCFList(e *ast.CallExpr, fName string) (cf check.String, err error) {
	errIntro := "can't make the " + strCFName +
		" func: " + fName + "(" + strCFName + " ...):"
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("%s %v", errIntro, r)
		}
	}()

	fArgs := make([]check.String, 0, len(e.Args))
	for i, argExpr := range e.Args {
		scf, err := getFuncStrCF(argExpr)
		if err != nil {
			return nil, fmt.Errorf("%s can't convert argument %d to %s: %s",
				errIntro, i, strCFName, err)
		}
		fArgs = append(fArgs, scf)
	}

	if f, ok := strCFStrCFList[fName]; ok {
		return f(fArgs...), nil
	}

	return nil, fmt.Errorf("%s the name is not recognised", errIntro)
}

// strCFParse returns a slice of string check functions and a nil error if
// the string is successfully parsed or nil and an error if the string
// couldn't be converted to a slice of check functions.
func stringCFParse(s string) ([]check.String, error) {
	elts, err := getElts(s, strCFDesc)

	if err != nil {
		return nil, err
	}

	rval := make([]check.String, 0, len(elts))
	for _, elt := range elts {
		f, err := getFuncStrCF(elt)
		if err != nil {
			return nil, fmt.Errorf("bad function: %s", err)
		}
		rval = append(rval, f)
	}

	return rval, nil
}

// getFuncStrCF will process the expression and return a string checker or
// nil
func getFuncStrCF(elt ast.Expr) (cf check.String, err error) {
	defer func() {
		if r := recover(); r != nil {
			cf = nil
			err = fmt.Errorf("Cannot create the %s func: %v", strCFName, r)
		}
	}()

	switch e := elt.(type) {
	case *ast.Ident:
		return makeStrCF(nil, e.Name)
	case *ast.CallExpr:
		fd, err := getFuncDetails(e, strCFName)
		if err != nil {
			return nil, err
		}

		maker, ok := strCFArgsToFunc[fd.expectedArgs]
		if !ok {
			return nil, fmt.Errorf("%s has an unrecognised argument list: %s",
				fd.name, fd.expectedArgs)
		}

		return maker(e, fd.name)
	}

	return nil, fmt.Errorf("unexpected type: %T", elt)
}
